services:
  webserver:
    container_name: django-docker-prod
    build: .
    command: gunicorn --config gunicorn_config.py launcher.wsgi:application
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
# sudo apt-get install certbot python3-certbot-nginx
# sudo certbot --nginx -d your-domain.com -d www.eventos.pi.gov.br
# sudo certbot --nginx -d your-domain.com -d eventos.pi.gov.br
# sudo certbot --nginx -d eventos.pi.gov.br
